export const materiaPrima = [
  'AGLOMERADO E COMPENSADO',
  'AREIA',
  'ARGILA',
  'BALATA',
  'BORRACHA',
  'CARCAÇA',
  'CASCA',
  'CASCO',
  'CAULE E RAIZ',
  'CERA',
  'CERÂMICA',
  'CHIFRE E OSSO',
  'CONCHA',
  'COURO E PELE',
  'COURO SINTÉTICO',
  'CRINA E PELO',
  'DENTE',
  'ESCAMA',
  'FIO DE LÃ',
  'FIO E FIBRA',
  'FIO E TECIDO',
  'FLOR',
  'FOLHA E FRUTO',
  'LÁTEX',
  'MADEIRA',
  'MASSA',
  'MASSA E RESINA',
  'MATERIAIS SINTÉTICOS',
  'MDF',
  'METAL',
  'PAPEL',
  'PEDRA',
  'PENA E PLUMA',
  'SEDA',
  'SEMENTE',
  'VIDRO',
];
